#! /bin/bash
echo "Instal firefox color theme"
wget http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_15.10/Release.key
sudo apt-key add - < Release.key
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_15.10/ /' >>  /etc/apt/sources.list.d/arc-theme.list"
sudo add-apt-repository -y ppa:moka/stable
sudo apt-get update
sudo apt-get install -y arc-theme
sudo apt-get install -y moka-icon-theme
